### ISSUE TITLE
Long text in editor becomes invisible when selecting and scrolling horizontally.  

### ISSUE THREAD

**Issue by mirzakhany** [oligo/gioview#12]
When editor is in Single line mode, Long text in editor becomes invisible when selecting and scrolling horizontally.  

Attached a video that shows the issue. the editor on the left is a normal gio editor and the right one is gioview editor with single line mode enabled.

https://github.com/user-attachments/assets/4d9baaba-42dd-40ee-895c-402abc530ab3

**Comment by oligo** [comment]
Did you do a diff with the gio editor regarding the single line mode code? I am not sure if some code is missing or not.

**Comment by mirzakhany** [comment]
There are some differences but not related to single line.
I have found something in text_iterator.go on this line:

```
	glyphOffset := op.Affine(f32.Affine2D{}.Offset(f32.Point{X: span.offset})).Push(gtx.Ops)
```
And `span.offset` is -1 until selection reach the end visible area. 

Original editor used `t.lineOff` here. I have tried with `t.lineOff.X`, as result selection looks working but text is not rendered correctly.  


https://github.com/user-attachments/assets/3cc60157-dcc6-41e0-bd53-08373728a201

**Comment by oligo** [comment]
Hi @mirzakhany ,

I think I solved this problem after a few hours debugging😂. The problem is related to offset calculating of the glyph group. For multi-line editor, this was never a problem because editor does not scroll horizontally, and this issue was never found.

I put the patch in the same branch as the line number feature, so you could test them using the same branch.

**Comment by mirzakhany** [comment]
Great job 💯  😆 Its working now!
